### ISSUE TITLE
一个mpc的教程 REMOVE ALL OF MY MPC CODE FROM YOUR WEBSITE!!

### ISSUE THREAD

**Issue by AleksandarHaber** [mathnovel/DayCollection#151]
### Discussed in https://github.com/mathnovel/DayCollection/discussions/145

YOU DO NOT HAVE THE PERMISSION TO USE MY GRAPHS, MY MPC CODE, OR ANYTHING ELSE FROM MY GITHUB IR WEBPAGE ON THIS REPOSITORY, IMMEDIATELY PUT IT DOWN

<div type='discussions-op-text'>

<sup>Originally posted by **mathnovel** December  1, 2024</sup>
https://aleksandarhaber.com/model-predictive-control-mpc-tutorial-2-unconstrained-solution-for-linear-systems-and-implementation-in-c-from-scratch-by-using-eigen-c-library/#google_vignette

https://github.com/mathnovel/Model-Predictive-Control-for-Linear-Systems-in-Cpp-by-Using-Eigen-Library

https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course</div>

**Comment by mathnovel** [comment]
already deleted all your code!

**Comment by AleksandarHaber** [comment]
YOU DID NOT ERASE THE DISCUSSION WHERE YOU HAVE UPLOADED TEXT, IMAGES, AND
OTHER MATERIAL FROM MY WEBSITE: BELOW IS THE LINK TO THIS DISCUSSION:

https://github.com/mathnovel/DayCollection/discussions/145

ERASE EVERY SINGLE PHOTO, PIECE OF TEXT, AND CODE THAT IS TAKEN FROM MY
WEBSITE.
