### ISSUE TITLE
Erase all of my MPC files from your repository

### ISSUE THREAD

**Issue by AleksandarHaber** [mathnovel/DayCollection#152]
You have reuploaded my MPC code on your GitHUb and you have violated the license!!

Erase this repository immediately! You are stealing other people's work. We will figure out who you are and we will take legal actions to prevent you to do this.

https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course

**Comment by mathnovel** [comment]
> You have reuploaded my MPC code on your GitHUb and you have violated the license!!
> 
> Erase this repository immediately! You are stealing other people's work. We will figure out who you are and we will take legal actions to prevent you to do this.
> 
> https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course

Sorry. I just save that code for personal learning,and thank you for your article.
Actually i have put the link of your repos at the beginning. I think this is enough if for personal learning ,not for commercial.
Your posted code can not be compiled directly,so i modify it to pass the compile step,and share for other beginning learner.
If you still think that  violated the license, i will remove the code later

**Comment by mathnovel** [comment]
> You have reuploaded my MPC code on your GitHUb and you have violated the license!!
> 
> Erase this repository immediately! You are stealing other people's work. We will figure out who you are and we will take legal actions to prevent you to do this.
> 
> https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course

I am really confused that since you put your code on Github,which means you allow other guys to fork the code for learning,but not for commercial. Buf from what you said,it seems you do not allow other people to fork your codes!!

**Comment by AleksandarHaber** [comment]
REMOVE THE CODE, FIGURES, POSTS, GRAPHS, ANY MATERIAL FROM MY GITHUB AND
WEBPAGE IMMEDIATELY! YOU HAVE VIOLATED THE COPYRIGHT AND THE LICENSE FROM
THE CODE AND WEBSITE. YOU ARE NOT ALLOWED TO REPOST THE CODE, TO MODIFY THE
CODE, TO REUPLOAD THE CODE, TO USE FIGURES, TEXT OR ANYTHING ELSE. YOU HAVE
1 HOUR TO DO THIS!!!
HERE ARE THE WEBSITES AND REPOSITORIES THAT NEED TO BE ERASED:

https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course


https://github.com/mathnovel/Model-Predictive-Control-for-Linear-Systems-in-Cpp-by-Using-Eigen-Library

https://github.com/mathnovel/DayCollection/discussions/145

**Comment by AleksandarHaber** [comment]
MY LAWYER WILL FIND YOU IN CHINA OR HONG KONG OR WHEREVER YOU ARE AND WE
WILL REPORT YOU TO THE YOUR GOVERNMENT FOR STEALING OTHER PEOPLE
INFORMATION.

  REMOVE THE CODE, FIGURES, POSTS, GRAPHS, ANY MATERIAL FROM MY GITHUB AND
WEBPAGE IMMEDIATELY! YOU HAVE VIOLATED THE COPYRIGHT AND THE LICENSE FROM
THE CODE AND WEBSITE. YOU ARE NOT ALLOWED TO REPOST THE CODE, TO MODIFY THE
CODE, TO REUPLOAD THE CODE, TO USE FIGURES, TEXT OR ANYTHING ELSE. YOU HAVE
1 HOUR TO DO THIS!!!
HERE ARE THE WEBSITES AND REPOSITORIES THAT NEED TO BE ERASED:

https://github.com/mathnovel/DayCollection/tree/main/mpc/a_mpc_course


https://github.com/mathnovel/Model-Predictive-Control-for-Linear-Systems-in-Cpp-by-Using-Eigen-Library

https://github.com/mathnovel/DayCollection/discussions/145

**Comment by mathnovel** [comment]
Respect your request

**Comment by AleksandarHaber** [comment]
ERASE ALL THE CODE AND GRAPHS YOU USED IN THE LINK BELOW. YOU HAVE VIOLATED
THE WEBSITE COPYRIGHT NOTICE BY REUPLOADING THE IMAGES, CODE, AND TEXT FROM
MY WEBSITE:

https://github.com/mathnovel/DayCollection/discussions/145

**Comment by AleksandarHaber** [comment]
> Respect your request

ERASE ALL THE CODE AND GRAPHS YOU USED IN THE LINK BELOW. YOU HAVE VIOLATED THE WEBSITE COPYRIGHT NOTICE BY REUPLOADING THE IMAGES, CODE, AND TEXT FROM MY WEBSITE:

https://github.com/mathnovel/DayCollection/discussions/145
